/**
 * Markdown report writer — GitHub-flavored Markdown suitable for pasting into
 * GitHub issues/PRs. Patterns are grouped by violation type.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { JsonReport } from './json.js';
import type { ViolationPattern } from '../analyzer/patterns.js';

const REPORTS_DIR = resolve(process.cwd(), 'reports');

/** Escape characters that have special meaning in Markdown inline code or text. */
function escapeMarkdown(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\|/g, '\\|')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/** Group patterns by violationId, preserving order of first appearance. */
function groupByViolation(
  patterns: ViolationPattern[]
): Map<string, { description: string; impact: string; fixUrl: string; patterns: ViolationPattern[] }> {
  const groups = new Map<
    string,
    { description: string; impact: string; fixUrl: string; patterns: ViolationPattern[] }
  >();

  for (const p of patterns) {
    if (!groups.has(p.violationId)) {
      groups.set(p.violationId, {
        description: p.violationDescription,
        impact: p.impact,
        fixUrl: p.suggestedFix,
        patterns: [],
      });
    }
    groups.get(p.violationId)!.patterns.push(p);
  }

  return groups;
}

function buildSummaryTable(
  groups: Map<string, { description: string; impact: string; fixUrl: string; patterns: ViolationPattern[] }>
): string {
  const lines: string[] = [
    '| Violation Type | Impact | Patterns | Affected Pages |',
    '|---|---|---|---|',
  ];

  for (const [violationId, group] of groups) {
    const totalPages = new Set(group.patterns.flatMap((p) => p.affectedUrls)).size;
    lines.push(`| ${escapeMarkdown(violationId)} | ${escapeMarkdown(group.impact)} | ${group.patterns.length} | ${totalPages} |`);
  }

  return lines.join('\n');
}

function buildPatternSection(p: ViolationPattern): string {
  const lines: string[] = [
    `### ${p.patternId} — ${escapeMarkdown(p.normalizedSelector)}`,
    `- **Impact:** ${escapeMarkdown(p.impact)}`,
    `- **Affected pages:** ${p.affectedPageCount}`,
    `- **Root cause:** ${escapeMarkdown(p.rootCauseHint)}`,
    `- **HTML snippet:** \`${escapeMarkdown(p.htmlSnippet)}\``,
    `- **Failure:** ${escapeMarkdown(p.failureSummary)}`,
    '',
    `<details><summary>Affected URLs (${p.affectedUrls.length})</summary>`,
    '',
    ...p.affectedUrls.map((u) => `- ${u}`),
    '</details>',
  ];

  return lines.join('\n');
}

function buildGroupSection(
  violationId: string,
  group: { description: string; impact: string; fixUrl: string; patterns: ViolationPattern[] }
): string {
  const lines: string[] = [
    `## ${escapeMarkdown(violationId)} (${escapeMarkdown(group.impact)})`,
    `> ${escapeMarkdown(group.description)}`,
    `> [Fix guide →](${group.fixUrl})`,
    '',
    ...group.patterns.map(buildPatternSection),
  ];

  return lines.join('\n');
}

function buildMarkdown(report: JsonReport): string {
  const { meta, patterns } = report;
  const groups = groupByViolation(patterns);

  const lines: string[] = [
    `# a11yscan Report — ${escapeMarkdown(meta.sitemap)}`,
    '',
    `**Generated:** ${meta.generatedAt} | **Pages scanned:** ${meta.pagesScanned} | **Patterns:** ${meta.totalPatterns} | **Violations:** ${meta.totalViolations}`,
    '',
  ];

  if (meta.interrupted) {
    lines.push(`> **Warning:** Scan was interrupted: ${escapeMarkdown(meta.interruptReason || 'unknown reason')}. Results below are partial.`);
    lines.push('');
  }

  lines.push('## Summary');

  if (patterns.length > 0) {
    lines.push(buildSummaryTable(groups));
    lines.push('');

    for (const [violationId, group] of groups) {
      lines.push(buildGroupSection(violationId, group));
      lines.push('');
    }
  } else {
    lines.push('');
    lines.push('No accessibility violations found.');
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by ${meta.tool} v${meta.version} on ${meta.generatedAt}`);

  return lines.join('\n');
}

/**
 * Write a Markdown report to disk.
 *
 * @returns The absolute path to the written Markdown file.
 */
export async function writeMarkdown(
  report: JsonReport,
  filename: string,
  siteReportsDir?: string
): Promise<string> {
  const dir = siteReportsDir || REPORTS_DIR;
  await mkdir(dir, { recursive: true });

  const filePath = join(dir, `${filename}.md`);
  await writeFile(filePath, buildMarkdown(report), 'utf-8');
  return filePath;
}
